import Head from "next/head";
import {
  useState,
  useRef,
  useEffect,
  forwardRef,
  useImperativeHandle,
} from "react";
const subjects = ["Mathematics", "English Language", "CRK", "Basic Science"];

const subjects2 = [
  { name: "Mathematics", score: 0 },
  { name: "English Language", score: 0 },
  { name: "CRK", score: 0 },
  { name: "Basic Science", score: 0 },
];
const cols = 9;
export default function Home() {
  const [state, setState] = useState(0);
  const ref = useRef(null);
  // const ref2 = useRef();

  // useEffect(() => console.log("Ref2: ", ref2?.current));

  const addData = (e) => {
    setState(() => state + Number(e.target.value));
    // console.log(state);
  };
  return (
    <div>
      <Head>
        <title> Create Next App </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container my-5 text-center">
        <div className="row border my-2">
          <div className="col-md-2 border"> Date of Birth </div>
          <div className="col-md-2 border">
            <input type="text" />
          </div>
          <div className="col-md-2 border"> Admission Number </div>
          <div className="col-md-2 border">
            <input type="text" />
          </div>
          <div className="col-md-2 border"> Admission Number </div>
          <div className="col-md-2 border">
            <input type="text" />
          </div>
        </div>
        <div className="row border my-2">
          <div className="col-md-2 border"> Session </div>
          <div className="col-md-1 border">
            <input style={{ width: "100%" }} type="text" />
          </div>
          <div className="col-md-2 border"> Term </div>
          <div className="col-md-1 border">
            <input style={{ width: "100%" }} type="text" />
          </div>
          <div className="col-md-2 border"> Admission Number </div>
          <div className="col-md-1 border">
            <input style={{ width: "100%" }} type="text" />
          </div>
          <div className="col-md-2 border"> Admission Number </div>
          <div className="col-md-1 border">
            <input style={{ width: "100%" }} type="text" />
          </div>
        </div>
        <div className="row">
          <div className="col-md-4 border"> </div>
          <div className="col-md-4 border"> </div>
          <div className="col-md-4 border"> </div>
        </div>
        <div className="row">
          <div className="col-md-12 table-responsive">
            <h3> Midterm Result </h3>
            <table className="table table-bordered ">
              <thead className="table-light">
                <tr>
                  <th scope="col"> </th>
                  <th scope="col" style={{ width: "20%" }}></th>
                  <th scope="col"> Project </th> <th scope="col"> Weekly </th>
                  <th scope="col"> Notes </th> <th scope="col"> First C.A. </th>
                  <th scope="col"> Total </th> <th scope="col"> Grade </th>
                  <th scope="col"> Sign. </th>
                </tr>
              </thead>
              <thead>
                <tr>
                  <th scope="col"> S.No </th>
                  <th scope="col" style={{ width: "20%" }}>
                    Subject
                  </th>
                  <th scope="col"> 5 </th> <th scope="col"> 3 </th>
                  <th scope="col"> 2 </th> <th scope="col"> 10 </th>
                  <th scope="col"> 20 </th> <th scope="col"> A1 - F9 </th>
                  <th scope="col"> </th>
                </tr>
              </thead>
              <tbody>
                {subjects2.map((x, i) => (
                  <MappedContent key={i} data={x} index={i} />
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <hr />
    </div>
  );
}

const MappedContent = ({ data, index }) => {
  const lead = ["Project", "Weekly", "Notes", "FirstCA"];
  const grades = [
    { grade: "A1", lowerLimit: 19.2, upperLimit: 20, gradePoint: 9 },
    { grade: "B2", lowerLimit: 18.2, upperLimit: 19.19, gradePoint: 8 },
    { grade: "B3", lowerLimit: 17.2, upperLimit: 18.19, gradePoint: 7 },
    { grade: "C4", lowerLimit: 16.2, upperLimit: 17.19, gradePoint: 6 },
    { grade: "C5", lowerLimit: 15.2, upperLimit: 16.19, gradePoint: 5 },
    { grade: "C6", lowerLimit: 14.2, upperLimit: 15.19, gradePoint: 4 },
    { grade: "D7", lowerLimit: 13.2, upperLimit: 14.19, gradePoint: 3 },
    { grade: "E8", lowerLimit: 12.2, upperLimit: 13.19, gradePoint: 2 },
    { grade: "F9", lowerLimit: 0, upperLimit: 12.2, gradePoint: 1 },
  ];
  const [state, setState] = useState({
    Project: 0,
    Weekly: 0,
    Notes: 0,
    FirstCA: 0,
  });
  const ref = useRef(null);
  const [total, setTotal] = useState(0);

  useEffect(() => {
    const t = Object.values(state).reduce((acc, curr) => acc + curr, 0);
    setTotal(t);
  }, [state.FirstCA, state.Notes, state.Project, state.Weekly]);
  const getScore = ({ target }) => {
    const name = target.name;
    const value = Number(target.value);
    setState({ ...state, [name]: value });
  };
  return (
    <tr key={`lol${data.name}`}>
      <th scope="row"> {index + 1} </th> <td> {data.name} </td>
      {lead.map((x, i) => (
        <td key={i}>
          <input name={x} type="number" onChange={getScore} />
        </td>
      ))}
      <td> {total} </td> <td> grade here </td> <td> sign here </td>
    </tr>
  );
};
